# -*- coding: utf-8 -*-
"""Passward generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19yFaVdpVh02KzywxJcn4GGALqdvmtL26
"""

import string
import random

def generate_password(length):
    all_characters = string.ascii_letters + string.digits + string.punctuation
    if length < 8:
        print("Password length should be at least 8")
        return None
    password = ''.join(random.choice(all_characters) for i in range(length))
    return password

def main():
    length = int(input("Enter the desired length of the password: "))
    password = generate_password(length)
    if password:
        print("Your password is: ", password)

if __name__ == "__main__":
    main()